### PR TITLE
add symlinks for Tilix

### PR DESCRIPTION
**Pull request by gabrielelucci**

### CODE REVIEW

**Comment by snwh** [comment]
The README wasn't "broken"

**Comment by gabrielelucci** [comment]
> The README wasn't "broken"

Not really broken, but sometimes this would happen to me, because there is no space after "#":

screen

This should not happen anymore. Also, a markdown file should be as human-readable as possible, and adding a space after "#" certainly impoves readability.

**Comment by gabrielelucci** [comment]
Ship it?

**Comment by snwh** [comment]
Fair enough

**Pull request merged**
