### PR TITLE
Pidgin icon

### PR DESCRIPTION
**Pull request by dernalis**

### CODE REVIEW

**Comment by snwh** [comment]
Um, there's 147 old commits in there.

**Comment by dernalis** [comment]
My first pull request, I made a mess with the branches, sorry. I will try again later.

**Comment by snwh** [comment]
I also plan on doing something specific for pidgin, instead of rehashing the chat icon in different colors over and over.

**Comment by dernalis** [comment]
Then, it will be a placeholder icon until you get a better one. =)

**Comment by snwh** [comment]
You can use it as a placeholder yourself, I'm not going to merge the one you've created into the main repo.

**Pull request closed without merging**
