### PR TITLE
Reducing icon size

### PR DESCRIPTION
**Pull request by now-im**
This is a very cool project. I have noticed the icon size is a tad big. I have reduced it using `svgcleaner`.  In most of the cases, it has saved more than 90% space. Just have a look.

### CODE REVIEW

**Comment by snwh** [comment]
NOOOO

**Comment by snwh** [comment]
This strips literally all of the necessary layers, etc. used for rendering the icons to PNG. The icons that are SVG (the symbolic icon set) are already minified.

**Comment by snwh** [comment]
Also, never open a pull request with 2000+ file changes that's impossible to review :joy:

**Comment by snwh** [comment]
SVG cleaners tend to be too aggressive and makes the icons impossible to edit. But yeah the icons are a tad oversized, I'll adjust the rendering script to have the icons be more minified when rendered and re-render all the panel and symbolic icons. Which should improve the situation.

**Comment by now-im** [comment]
That is great to hear. I will close the merge then. Thanks for your time.

**Pull request closed without merging**
