### PR TITLE
Google chrome additional icons

### PR DESCRIPTION
**Pull request by nlaplante**
Added symlinks for google-chrome-beta and google-chrome-unstable, since Google's desktop entries references those icon names in their beta and unstable Chrome versions.

### CODE REVIEW

**Comment by nlaplante** [comment]
This would close #17

**Comment by snwh** [comment]
Not quite. These are direct links that will only work for you –I've fixed #17 in with the latest commit.

**Comment by nlaplante** [comment]
I tought my second commit fixed the absolute links ?!?!

**Comment by snwh** [comment]
The third commit added absolute symlinks.

**Comment by nlaplante** [comment]
Ok. Weird, the third commit here shows 0 changed files. Anyway :) thanks for handling this!

**Comment by snwh** [comment]
I also don't need "merge" commits in the master branch; as few commits as possible for merge requests is ideal.

**Pull request closed without merging**
