### PR TITLE
Symlinks

### PR DESCRIPTION
**Pull request by poltertec**
Added some symlinks for Budgie menu
(and nice tweaks on the plex icon btw :))

### CODE REVIEW

**Comment by snwh** [comment]
`gnome-settings` isn't a standard icon and I don't agree with using the text-editor icon for the Office category.

**Comment by poltertec** [comment]
gnome-settings is needed for the System Settings categorie in budgie menu.
Perhaps gnome-docs icon would be better suited for the Office category?

**Comment by snwh** [comment]
Hmm, perhaps I'll bug @ikeydoherty to change it to the more appropriate `preferences-system` icon.

**Comment by snwh** [comment]
I guess I'll make an Office icon today –I've just not had a good idea for one yet.

**Comment by poltertec** [comment]
Any idea is better then the Adwaita one in my opinion :D

**Comment by poltertec** [comment]
I'm also looking for something to do with the applications-accessories & applications-other categorie icons

**Comment by poltertec** [comment]
What i had for applications-accessories so far 
applications-accessories

**Comment by ikeydoherty** [comment]
@snwh the icon name comes from libgnome-menus

**Comment by snwh** [comment]
@ikeydoherty I noticed that after poking through the Budgie code

**Comment by snwh** [comment]
@poltertec so the Glade icon plus the Android SDK icon ;)

**Comment by poltertec** [comment]
@snwh  indeed didn't commit with a reason :D

**Comment by ikeydoherty** [comment]
@snwh I might be able to add some icon mapping table to do replacements

**Comment by snwh** [comment]
@ikeydoherty don't go out of your way.

**Pull request closed without merging**
