### PR TITLE
Changed list symbolic icons

### PR DESCRIPTION
**Pull request by ArtyomZorin**
Made them look less like a hamburger menu icon, which was somewhat confusing

### CODE REVIEW

**Comment by snwh** [comment]
There is no hamburger menu icon in Paper.

**Comment by ArtyomZorin** [comment]
I agree with not using the hamburger menu icon as the overflow menu in Paper. However, using an icon that looks like the hamburger menu for the list view might confuse some new users who are accustomed to that icon being used for an application menu when using other platforms or devices (eg. Android), where this is a standardised metaphor.

Take this screenshot. It might not be clear which icon is the menu and which is the view-change one for new users:
screenshot from 2016-05-21 14-16-19

While here, the meaning of the list icon is clear while not being confused with the menu metaphor:
screenshot from 2016-05-21 14-13-14

The GNOME developers made a very similar change in recent versions of the Adwaita icon theme.

**Comment by snwh** [comment]
>  (eg. Android), where this is a standardised metaphor.
There is no standard menu icon throughout android apps. even from Google. Google+ for instance uses both.

Okay, I concede the overall point.

**Comment by ArtyomZorin** [comment]
Thanks for accepting the pull request and for your work on this icon theme!

**Pull request merged**
